name: rimucloud
services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: rimucloud-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    # restart: always
  webapi:
    build:
      context: .
      dockerfile: src/RimuCloud.ApiService/Dockerfile
    container_name: rimucloud-webapi
    # ports:
    #   - "${WEB_API_PORT}:8080"
    environment:
      - TZ=${TZ}
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DbConfig__Host=postgres
      - DbConfig__Port=5432
      - DbConfig__User=${POSTGRES_USER}
      - DbConfig__Password=${POSTGRES_PASSWORD}
      - DbConfig__DbName=${POSTGRES_DB}
    volumes:
      - ./.docker-volumes/webapi/logs:/var/log
    depends_on:
      migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    # restart: always
  migration:
    build:
      context: .
      dockerfile: src/RimuCloud.MigrationService/Dockerfile
    container_name: rimucloud-migration
    environment:
      - TZ=${TZ}
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - DOTNET_ENVIRONMENT=Development
      - DbConfig__Host=postgres
      - DbConfig__Port=5432
      - DbConfig__User=${POSTGRES_USER}
      - DbConfig__Password=${POSTGRES_PASSWORD}
      - DbConfig__DbName=${POSTGRES_DB}
    volumes:
      - ./.docker-volumes/migration/logs:/var/log
    #restart: always
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    image: nginx:stable-alpine
    container_name: rimucloud-nginx
    ports:
      - 80:80
      - "${NGINX_LISTEN_PORT}:443"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./conf/nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - webapi
# volumes:
#   postgres_data:
#   solr_data:
  
